language: java
before_install:
  - chmod +x gradlew
after_success:
  - export RELEASE_FILE=$(ls build/libs/jadget-exception*.jar)
  - echo "deploying $RELEASE_FILE to GitHub releases"
before_deploy:
  - export RELEASE_FILE=$(ls build/libs/jadget-exception*.jar)
  - echo "deploying $RELEASE_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: VhggDJKzw8Qdrnq4EdNwJXUFFyCMy2wd94UWPwXg9Ec3tkgRLVhvk1BQ2RzUIlfqXa6zbuUOEWeW4qfeWS/ununuKz0qhjzpLb8XYiwteYdcka6w07Ydd3sVxkyZPgwVzHbSy9//peQdb6oy7TfOAv0x7V5aOinIWyf5QAcd2Ho3C5GraX4pZpIFQvTCxMC6qbBJ+cVFBVE7oG2HDRthLjqLNcDHL6dW4RfDpuF93DGpu5wJF8LjCiezK1sWV7C4EAaNZMcaoRO1c8Ilg0CWs0h749ZX7YUEq1rl3w4cTI84mCYCbDPFKSOsvU3dck4CrTo2dEtr0ZLFwLu3DNC6qGq6bwxYO/CH2xmKLCd14nuLuj4pJS2fGgcZyJl0FZqLdbyokFTfVZ1qtBmOclhMJldvhbutaDVk7SnpuYEMmqzMJxo8neZ+CVUbh1uhWg2rFRbCF8cT38ulUE4N7gsk5lcltgoBrQ8q4iGK06IEFKpL5j7N0M+wDFOPka1Ae7a0bMvtoY1AlKm6x6vU2etEDzJmoD/uBXN2U03zY8yRaTLvGsShVoKfoXWVvPE9XbB5e45CBM1WCcQ7mPdybGgMv2P+K31f/xN6eGfy74n4DqdBBAoC+Syc+roN3A+m1Z/YtvOcFQveT67sMatEvaccdZv/00iJW+TQQ/MLhrvAbB4=
  file: "${RELEASE_FILE}"
  on:
    repo: jadget/jadget-exception
    tags: true
    all_branches: true
